export const SITE_CONFIG = {
  name: "Abscod Informatics",
  domain: "abscod.com",
  url: "https://abscod.com",
  description: "Abscod Informatics is a leading mobile app development and web design company. We develop customized mobile applications that are compatible with iOS and Android.",
  tagline: "Custom Mobile App Development Company",
  email: "contact@abscod.com",
  phone: "+1 (555) 123-4567",
  skype: "abscodinformatics",
  foundedYear: 2014,
  offices: [
    {
      country: "USA",
      city: "New York",
      phone: "+1 (555) 123-4567",
      email: "contact.us@abscod.com",
    },
    {
      country: "UK",
      city: "London",
      phone: "+44 20 7123 4567",
      email: "contact.uk@abscod.com",
    },
    {
      country: "India",
      city: "Bangalore",
      phone: "+91 80 1234 5678",
      email: "contact.in@abscod.com",
    },
    {
      country: "UAE",
      city: "Dubai",
      phone: "+971 4 123 4567",
      email: "contact.ae@abscod.com",
    },
  ],
};

export const SERVICE_CATEGORIES = [
  {
    title: "Designing Services",
    slug: "designing-services",
    icon: "Palette",
    description: "Creative design solutions that captivate your audience",
    services: [
      { name: "User Experience Design", slug: "user-experience-design" },
      { name: "User Interface Design", slug: "user-interface-design" },
      { name: "Mobile App Design", slug: "mobile-app-design" },
      { name: "Web Interface Design", slug: "web-interface-design" },
      { name: "Wireframe Prototyping", slug: "wireframe-prototyping" },
    ],
  },
  {
    title: "Web Development",
    slug: "web-development",
    icon: "Globe",
    description: "Robust web solutions for your digital presence",
    services: [
      { name: "Web Development Company", slug: "web-development-company" },
      { name: "Business Website", slug: "business-website" },
      { name: "Landing Pages", slug: "landing-pages" },
      { name: "CMS Development", slug: "cms-development" },
    ],
  },
  {
    title: "E-Commerce Solution",
    slug: "e-commerce-solution",
    icon: "ShoppingCart",
    description: "Complete e-commerce solutions to grow your online business",
    services: [
      { name: "E-commerce Website", slug: "e-commerce-website" },
      { name: "E-commerce Optimization", slug: "e-commerce-optimization" },
      { name: "Payment Gateway Integration", slug: "payment-gateway-integration" },
      { name: "Marketplace Development", slug: "marketplace-development" },
    ],
  },
  {
    title: "Software Development",
    slug: "software-development",
    icon: "Code",
    description: "Custom software solutions for your business needs",
    services: [
      { name: "Software Development Company", slug: "software-development-company" },
      { name: "Web Application Development", slug: "web-application-development" },
      { name: "Mobile Application Development", slug: "mobile-application-development" },
      { name: "Social Apps Development", slug: "social-apps-development" },
    ],
  },
  {
    title: "Mobile App Development",
    slug: "mobile-app-development",
    icon: "Smartphone",
    description: "Native and cross-platform mobile applications",
    services: [
      { name: "iOS App Development", slug: "ios-app-development" },
      { name: "Android App Development", slug: "android-app-development" },
      { name: "React Native Development", slug: "react-native-development" },
      { name: "Flutter Development", slug: "flutter-development" },
    ],
  },
  {
    title: "Cloud & DevOps",
    slug: "cloud-devops",
    icon: "Cloud",
    description: "Cloud infrastructure and DevOps automation",
    services: [
      { name: "Cloud Migration", slug: "cloud-migration" },
      { name: "AWS Services", slug: "aws-services" },
      { name: "DevOps Consulting", slug: "devops-consulting" },
      { name: "CI/CD Implementation", slug: "ci-cd-implementation" },
    ],
  },
];

export const SERVICES = [
  {
    slug: "mobile-application-development",
    title: "Mobile Application Development",
    shortTitle: "Mobile Apps",
    description: "At Abscod Informatics, an apt and efficient cross-functional team is always on a lookout for challenges that ask for creating visually stunning & functionally effective mobile apps.",
    metaDescription: "Top mobile app development company. We create stunning iOS and Android apps using React Native, Flutter, and native technologies. Start your project today.",
    icon: "Smartphone",
    features: [
      "iOS App Development",
      "Android App Development",
      "Cross-platform Development",
      "App Store Optimization",
      "Push Notifications",
      "Offline Functionality",
    ],
    benefits: [
      "Reach customers on any device",
      "Enhanced brand visibility",
      "Improved customer engagement",
      "Streamlined business processes",
      "Competitive market advantage",
      "Revenue generation opportunities",
    ],
    technologies: ["Swift", "Objective-C", "Java", "Kotlin", "React Native", "Flutter", "Xamarin", "Ionic"],
  },
  {
    slug: "web-development",
    title: "Web Development",
    shortTitle: "Web Development",
    description: "Modern, responsive web applications built with cutting-edge technologies for optimal performance and user experience.",
    metaDescription: "Professional web development services. Build fast, secure, and scalable websites with React, Next.js, and modern technologies. Request a quote now.",
    icon: "Globe",
    features: [
      "Progressive Web Apps (PWA)",
      "Single Page Applications (SPA)",
      "E-commerce Platforms",
      "Content Management Systems",
      "Real-time Applications",
      "API Development",
    ],
    benefits: [
      "Cross-platform compatibility",
      "SEO-friendly architecture",
      "Fast loading speeds",
      "Enhanced user engagement",
      "Easy maintenance and updates",
      "Cost-effective solution",
    ],
    technologies: ["React", "Next.js", "Vue.js", "Angular", "Node.js", "TypeScript", "PHP", "Laravel"],
  },
  {
    slug: "designing-services",
    title: "Designing Services",
    shortTitle: "UI/UX Design",
    description: "User-centered design solutions that create intuitive, engaging, and visually stunning digital experiences.",
    metaDescription: "Professional UI/UX design services for web and mobile applications. User research, wireframing, prototyping, and visual design.",
    icon: "Palette",
    features: [
      "User Experience Design",
      "User Interface Design",
      "Mobile App Design",
      "Web Interface Design",
      "Wireframe Prototyping",
      "Design System Creation",
    ],
    benefits: [
      "Increased user satisfaction",
      "Higher conversion rates",
      "Reduced development costs",
      "Stronger brand identity",
      "Improved user retention",
      "Competitive differentiation",
    ],
    technologies: ["Figma", "Adobe XD", "Sketch", "InVision", "Principle", "Framer"],
  },
  {
    slug: "e-commerce-solution",
    title: "E-Commerce Solution",
    shortTitle: "E-Commerce",
    description: "Complete e-commerce solutions to help you sell online effectively and grow your business.",
    metaDescription: "E-commerce development services. Build powerful online stores with Shopify, WooCommerce, Magento. Payment integration and optimization.",
    icon: "ShoppingCart",
    features: [
      "E-commerce Website Development",
      "Shopping Cart Integration",
      "Payment Gateway Setup",
      "Inventory Management",
      "Order Management System",
      "Multi-vendor Marketplace",
    ],
    benefits: [
      "24/7 online sales",
      "Global market reach",
      "Reduced operational costs",
      "Customer insights & analytics",
      "Scalable business growth",
      "Automated processes",
    ],
    technologies: ["Shopify", "WooCommerce", "Magento", "BigCommerce", "Stripe", "PayPal"],
  },
  {
    slug: "software-development",
    title: "Software Development",
    shortTitle: "Software Dev",
    description: "Custom software solutions designed to meet your unique business requirements and drive digital transformation.",
    metaDescription: "Expert custom software development services. We build scalable, secure, and innovative software solutions tailored to your business needs.",
    icon: "Code",
    features: [
      "Custom Software Development",
      "Enterprise Applications",
      "SaaS Development",
      "Legacy Modernization",
      "API Development",
      "Database Design",
    ],
    benefits: [
      "Tailored to your exact needs",
      "Competitive advantage",
      "Full ownership of code",
      "Scalable architecture",
      "Reduced operational costs",
      "Enhanced productivity",
    ],
    technologies: ["React", "Node.js", "Python", "Java", ".NET", "PostgreSQL", "MongoDB", "AWS"],
  },
  {
    slug: "cloud-devops",
    title: "Cloud & DevOps",
    shortTitle: "Cloud & DevOps",
    description: "Comprehensive cloud infrastructure and DevOps services to optimize your operations and accelerate deployment.",
    metaDescription: "Enterprise cloud solutions and DevOps services. AWS, Azure, GCP expertise. CI/CD pipelines, infrastructure automation.",
    icon: "Cloud",
    features: [
      "Cloud Migration Services",
      "Infrastructure as Code",
      "CI/CD Pipeline Setup",
      "Container Orchestration",
      "Monitoring & Logging",
      "Security & Compliance",
    ],
    benefits: [
      "Reduced infrastructure costs",
      "Faster time to market",
      "Improved reliability",
      "Automatic scaling",
      "Enhanced security",
      "Streamlined workflow",
    ],
    technologies: ["AWS", "Azure", "Google Cloud", "Docker", "Kubernetes", "Terraform", "Jenkins"],
  },
];

export const TESTIMONIALS = [
  {
    name: "Sarah Johnson",
    role: "CTO",
    company: "TechVentures Inc.",
    content: "Abscod Informatics transformed our legacy systems into a modern, scalable platform. Their expertise and dedication exceeded our expectations.",
    rating: 5,
  },
  {
    name: "Michael Chen",
    role: "Founder",
    company: "StartupFlow",
    content: "Working with Abscod was a game-changer for our startup. They delivered our MVP in record time without compromising on quality.",
    rating: 5,
  },
  {
    name: "Emily Rodriguez",
    role: "Product Manager",
    company: "GlobalRetail Corp",
    content: "The mobile app Abscod developed for us has significantly improved our customer engagement. Professional team with excellent communication.",
    rating: 5,
  },
  {
    name: "David Thompson",
    role: "IT Director",
    company: "FinanceHub",
    content: "Their cloud migration expertise saved us 40% on infrastructure costs. Highly recommend their DevOps services.",
    rating: 5,
  },
];

export const STATS = [
  { value: "1000+", label: "Projects Launched" },
  { value: "700+", label: "Satisfied Customers" },
  { value: "1200+", label: "Man Years Experience" },
  { value: "98%", label: "Client Retention" },
];

export const INDUSTRIES = [
  { name: "Real Estate Application", slug: "real-estate-app", icon: "Building2" },
  { name: "Taxi Application", slug: "taxi-app", icon: "Car" },
  { name: "Educational Application", slug: "education-app", icon: "GraduationCap" },
  { name: "Grocery & eCommerce", slug: "grocery-ecommerce", icon: "ShoppingBag" },
  { name: "Healthcare Application", slug: "healthcare-app", icon: "Heart" },
  { name: "Travel & Tourism", slug: "travel-tourism", icon: "Plane" },
  { name: "Bank & Finance", slug: "bank-finance", icon: "Landmark" },
  { name: "Logistics & Transport", slug: "logistics-transport", icon: "Truck" },
];

export const ON_DEMAND_SERVICES = [
  "Taxi App Development",
  "Food Delivery App",
  "Grocery Delivery App",
  "Healthcare App",
  "Real Estate App",
  "E-Learning App",
  "Fitness App",
  "Dating App",
  "Hotel Booking App",
  "Handyman App",
  "Laundry App",
  "Beauty & Salon App",
];

export const NAV_LINKS = [
  { href: "/", label: "Home" },
  { href: "/services", label: "Services" },
  { href: "/portfolio", label: "Portfolio" },
  { href: "/about", label: "About Us" },
  { href: "/contact", label: "Contact Us" },
];

export const CLIENTS = [
  "TechCorp", "InnovateTech", "GlobalSoft", "DataDriven", "CloudFirst",
  "MobileMax", "WebWorks", "AppGenius", "CodeCraft", "DigitalEdge",
];
